// Phase 14 execution pipeline.
// Validates → Compiles → Phase 12 pre-verify → Phase 13 bootloader.
// No mutation path exists outside this pipeline.

import { readFileSync, writeFileSync, unlinkSync, existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { ProposalDiffV1Schema } from './schema';
import { validateComposition } from './composition';
import { compileProposal } from './phase14-compiler';
import { createProposal, submitForApproval } from '../governance/proposer';
import { applyProposalTransition } from '../governance/ledger';
import { runBootloader } from '../governance/bootloader';
import type { PipelineResult, PipelineOptions } from './schema';

const PROJECT_ROOT = resolve(__dirname, '..', '..');
const TSX_BIN      = resolve(PROJECT_ROOT, 'node_modules', '.bin', 'tsx');
const TLA_PATH     = resolve(PROJECT_ROOT, 'formal_specs', 'efsm.tla');
const SM_PATH      = resolve(PROJECT_ROOT, 'src', 'efsm', 'state-machine.ts');
const STAGED_TLA   = resolve(PROJECT_ROOT, 'formal_specs', 'efsm.staged.tla');
const STAGED_SM    = resolve(PROJECT_ROOT, 'src', 'efsm', 'state-machine.staged.ts');

// ── File assembly helpers ─────────────────────────────────────────────────────

// Build new TLA+ spec by inserting operator blocks before the Next relation
// and adding them to the Next disjunction, or removing them.
function assembleTlaSpec(patches: string[]): string {
  let spec = readFileSync(TLA_PATH, 'utf8');

  for (const patch of patches) {
    if (patch.startsWith('REMOVE:')) {
      const opName = patch.slice('REMOVE:'.length).trim();
      // Remove the operator block (from name(t) == to the blank line after it).
      const blockPattern = new RegExp(
        `\n${opName}\\(t\\) ==\\n(?:[^\\n]*\\n)*?(?=\\n)`,
        'g',
      );
      spec = spec.replace(blockPattern, '');
      // Remove from Next relation.
      spec = spec.replace(new RegExp(`\\s*\\\\\\/\\s*${opName}\\(t\\)`, 'g'), '');
    } else if (patch.startsWith('REMOVE_INVARIANT:')) {
      const name = patch.slice('REMOVE_INVARIANT:'.length).trim();
      // Remove invariant block (name == ... up to blank line).
      const blockPattern = new RegExp(`\n${name} ==\\n(?:[^\\n]*\\n)*?(?=\\n)`, 'g');
      spec = spec.replace(blockPattern, '');
    } else if (patch.includes('(t) ==')) {
      // New operator block — insert before the Next relation section.
      const nextIdx = spec.indexOf('\n\\* Next relation');
      if (nextIdx === -1) throw new Error('Cannot find Next relation section in efsm.tla');
      const opName = patch.split('(t) ==')[0]!.trim();
      // Insert operator block before the Next relation.
      spec = spec.slice(0, nextIdx) + '\n\n' + patch + '\n' + spec.slice(nextIdx);
      // Add to the Next relation's disjunction after the last \\/ line.
      const lines = spec.split('\n');
      let lastDisjIdx = -1;
      for (let i = 0; i < lines.length; i++) {
        if (/^\s*\\\/\s*\w+\(t\)$/.test(lines[i]!)) lastDisjIdx = i;
      }
      if (lastDisjIdx >= 0) {
        lines.splice(lastDisjIdx + 1, 0, `    \\/ ${opName}(t)`);
        spec = lines.join('\n');
      }
    } else {
      // Invariant block — insert before the Spec section.
      const specIdx = spec.indexOf('\n\\* Full specification');
      if (specIdx === -1) throw new Error('Cannot find Full specification section in efsm.tla');
      spec = spec.slice(0, specIdx) + '\n\n' + patch + '\n' + spec.slice(specIdx);
    }
  }

  return spec;
}

// Build new state-machine.ts by inserting / removing projection entries.
function assembleStateMachine(projectionUpdates: string[]): string {
  let content = readFileSync(SM_PATH, 'utf8');

  for (const update of projectionUpdates) {
    if (update.startsWith('REMOVE:')) {
      const projection = update.slice('REMOVE:'.length).trim();
      // Remove the exact line from the array.
      content = content.replace(`\n  "${projection}",`, '');
    } else {
      // Insert projection before the closing ]; of TRANSITION_SQL_PROJECTIONS.
      const arrayStart = content.indexOf('TRANSITION_SQL_PROJECTIONS');
      const closingIdx = content.indexOf('];', arrayStart);
      if (closingIdx === -1) throw new Error('Cannot find TRANSITION_SQL_PROJECTIONS closing bracket');
      content = content.slice(0, closingIdx) + `  "${update}",\n` + content.slice(closingIdx);
    }
  }

  return content;
}

// Build SQL migration file content from DDL statements.
function assembleMigrationSql(sqlStatements: string[], opTypes: string[]): string {
  const header = `-- Generated by Phase 14 compiler\n-- Operations: ${opTypes.join(', ')}\n\n`;
  return header + sqlStatements.join('\n\n') + '\n';
}

// Build capability migration SQL content.
function assembleCapabilityMigration(capabilityUpdates: string[], opTypes: string[]): string {
  const header = `-- Generated by Phase 14 compiler (capability)\n-- Operations: ${opTypes.join(', ')}\n\n`;
  return header + capabilityUpdates.join('\n\n') + '\n';
}

// ── Migration file naming ─────────────────────────────────────────────────────

function nextMigrationPath(suffix: string): string {
  const migDir = resolve(PROJECT_ROOT, 'src', 'migrations');
  const existing = readdirSync(migDir)
    .filter(f => /^\d{4}_.*\.sql$/.test(f) && !f.endsWith('.rollback.sql'))
    .sort();
  const lastNum = existing.length > 0
    ? parseInt(existing[existing.length - 1]!.slice(0, 4), 10)
    : 0;
  const next = String(lastNum + 1).padStart(4, '0');
  return resolve(migDir, `${next}_${suffix}.sql`);
}

// ── Phase 12 pre-verification ─────────────────────────────────────────────────

function preVerify(stagedTla?: string, stagedSm?: string): boolean {
  const env: NodeJS.ProcessEnv = { ...process.env };
  if (stagedTla) env['VERIFY_TLA_PATH'] = stagedTla;
  if (stagedSm)  env['VERIFY_SM_PATH']  = stagedSm;
  try {
    execFileSync(TSX_BIN, ['scripts/verify-efsm.ts'], { cwd: PROJECT_ROOT, env, stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

function cleanup(...paths: string[]): void {
  for (const p of paths) {
    if (existsSync(p)) { try { unlinkSync(p); } catch { /* best-effort */ } }
  }
}

// ── Public pipeline entry point ───────────────────────────────────────────────

export function executeProposalPipeline(
  rawInput: unknown,
  proposalId: string,
  justification: string,
  now: number,
  opts: PipelineOptions = {},
): PipelineResult {

  // ── Zod validation (hard gate) ───────────────────────────────────────────
  const parsed = ProposalDiffV1Schema.safeParse(rawInput);
  if (!parsed.success) {
    return {
      status: 'validation_error',
      reason: parsed.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; '),
    };
  }
  const diff = parsed.data;

  // ── Composition validation (hard gate) ──────────────────────────────────
  // Prevents "legal but lethal" same-entity contradictions and order-unsafe
  // combinations. Also normalizes ops into canonical sort order before compile.
  const composition = validateComposition(diff.ops);
  if (!composition.valid) {
    return {
      status: 'validation_error',
      reason: `Composition violations: ${composition.violations.join('; ')}`,
    };
  }
  const normalizedDiff = { version: 'v1' as const, ops: composition.normalizedOps as typeof diff.ops };

  // ── Deterministic compilation (on normalized ops) ────────────────────────
  let artifact;
  try {
    artifact = compileProposal(normalizedDiff);
  } catch (e: unknown) {
    return {
      status: 'compile_error',
      reason: e instanceof Error ? e.message : String(e),
    };
  }

  const opTypes = diff.ops.map(op => op.type);
  const hasTlaChanges         = artifact.tlaSpecPatches.length > 0;
  const hasProjectionChanges  = artifact.projectionUpdates.length > 0;
  const hasSqlMigrations      = artifact.sqlMigrations.length > 0;
  const hasCapabilityUpdates  = artifact.capabilityUpdates.length > 0;

  // ── Stage files + Phase 12 pre-verification ──────────────────────────────
  const stagedFiles: string[] = [];
  let stagedTlaForVerify: string | undefined;
  let stagedSmForVerify:  string | undefined;

  try {
    if (hasTlaChanges) {
      const newSpec = assembleTlaSpec(artifact.tlaSpecPatches);
      writeFileSync(STAGED_TLA, newSpec, 'utf8');
      stagedFiles.push(STAGED_TLA);
      stagedTlaForVerify = STAGED_TLA;
    }
    if (hasProjectionChanges) {
      const newSm = assembleStateMachine(artifact.projectionUpdates);
      writeFileSync(STAGED_SM, newSm, 'utf8');
      stagedFiles.push(STAGED_SM);
      stagedSmForVerify = STAGED_SM;
    }
  } catch (e: unknown) {
    cleanup(...stagedFiles);
    return {
      status: 'compile_error',
      reason: `File assembly failed: ${e instanceof Error ? e.message : String(e)}`,
    };
  }

  const verifyPassed = preVerify(stagedTlaForVerify, stagedSmForVerify);
  cleanup(...stagedFiles);

  if (!verifyPassed) {
    return { status: 'verification_failed', reason: 'Phase 12 pre-verification failed', artifact };
  }

  // ── Phase 13 proposals ───────────────────────────────────────────────────
  const proposalIds: string[] = [];
  const bootloaderTargets: Array<{ pid: string; targetFile: string; content: string; layer: 'TLA_SPEC' | 'SQL_MIGRATION' | 'CAPABILITY_REGISTRY' }> = [];

  // TLA+ spec update
  if (hasTlaChanges) {
    const newSpec = assembleTlaSpec(artifact.tlaSpecPatches);
    bootloaderTargets.push({ pid: `${proposalId}-tla`, targetFile: 'formal_specs/efsm.tla', content: newSpec, layer: 'TLA_SPEC' });
  }
  // SQL projection update (state-machine.ts via CAPABILITY_REGISTRY layer)
  if (hasProjectionChanges) {
    const newSm = assembleStateMachine(artifact.projectionUpdates);
    bootloaderTargets.push({ pid: `${proposalId}-sm`, targetFile: 'src/efsm/state-machine.ts', content: newSm, layer: 'CAPABILITY_REGISTRY' });
  }
  // SQL migration file
  if (hasSqlMigrations) {
    const targetFile = opts.migrationTargetFile ?? nextMigrationPath(opTypes.join('_').toLowerCase());
    const content    = assembleMigrationSql(artifact.sqlMigrations, opTypes);
    bootloaderTargets.push({ pid: `${proposalId}-sql`, targetFile: resolve(PROJECT_ROOT, targetFile).replace(PROJECT_ROOT + '/', ''), content, layer: 'SQL_MIGRATION' });
  }
  // Capability migration file
  if (hasCapabilityUpdates) {
    const targetFile = opts.migrationTargetFile ?? nextMigrationPath(`${opTypes.join('_').toLowerCase()}_capabilities`);
    const content    = assembleCapabilityMigration(artifact.capabilityUpdates, opTypes);
    bootloaderTargets.push({ pid: `${proposalId}-cap`, targetFile: resolve(PROJECT_ROOT, targetFile).replace(PROJECT_ROOT + '/', ''), content, layer: 'SQL_MIGRATION' });
  }

  // Create, approve, and run bootloader for each proposal
  for (const target of bootloaderTargets) {
    try {
      createProposal({
        id:           target.pid,
        target_layer: target.layer,
        diff:         { targetFile: target.targetFile, content: target.content },
        justification,
      }, now);
      submitForApproval(target.pid, now + 1);
      applyProposalTransition(target.pid, 'PENDING_APPROVAL', 'APPROVED', now + 2);
    } catch (e: unknown) {
      return {
        status: 'compile_error',
        reason: `Proposal creation failed for ${target.pid}: ${e instanceof Error ? e.message : String(e)}`,
        artifact,
      };
    }

    const result = runBootloader(target.pid, now + 3);
    proposalIds.push(target.pid);

    if (result.status !== 'merged') {
      return {
        status: result.status === 'lock_failed' ? 'lock_failed' : 'verification_failed',
        reason: result.reason,
        proposalIds,
        artifact,
      };
    }
  }

  return { status: 'committed', proposalIds, artifact };
}
